hmacproxy:
  signer:
    enabled: true
    credential:
      id: 123abc
      secret: 123abc456def
      region: quay
      service: clair
    listenerAddr: ":8080"
  verifier:
    enabled: false
    upstream: http://localhost:6060
    maxClockSkew: 15s
    tls:
      certFile: ssl.crt
      keyFile: ssl.key
      cafile: ca.crt
      requireClientCertificate: false
    credentialSource:
      type: SingleCredential
      options:
        keyID: 123abc
        keySecret: 123abc456def
        keyRegion: quay
        keyService: quay
